version: "3.8"

services:
  pyspark:
    build: .
    container_name: pyspark_app
    working_dir: /usr/src/app   
    volumes:
      - ./Raw:/usr/src/app/Raw      
      - ./Trusted:/usr/src/app/Trusted
      - ./Refined:/usr/src/app/Refined
    environment:
      - JAVA_HOME=/usr/lib/jvm/default-java
    env_file:
    - .env
